const services={
 premium:{name:"Premium",mark:"P",desc:"",plans:[["1 Month",""],["3 Months","$3.99"],["6 Months","$6.49"],["12 Months","$10.99"]]},
 stars:{name:"Stars",mark:"S",desc:"",plans:[["50 Stars","$0.99"],["100 Stars","$1.89"],["150 Stars","$2.79"],["200 Stars","$3.69"],["250 Stars","$4.59"]]},
 boost:{name:"Boost",mark:"B",desc:"",plans:[["1 Day","$0.99"],["1 Month","$8.99"],["3 Months","$19.99"],["6 Months","$29.99"],["1 Year","$49.99"]]},
 nft:{name:"NFT",mark:"N",desc:""}
};
const NFT_SOURCE="https://raw.githubusercontent.com/ssamy2/TelegramGiftsAssests/main/Gifts_Details.json";
const NFT_BASE="https://raw.githubusercontent.com/ssamy2/TelegramGiftsAssests/main/";
const BACKDROP_SOURCE="https://cdn.jsdelivr.net/gh/ssamy2/TelegramGiftsAssests@main/backdrops/";
const MODEL_ASSET_BASE="https://raw.githubusercontent.com/ssamy2/TelegramGiftsAssests/main/models/";
const TON_TO_USD=1.54;
const USD_TO_TOMAN=268800;
const NFT_COST_BUFFER=0.03;
const NFT_PROFIT=0.10;
let nftSourcePromise=null;
const nftAttrCache=new Map();
async function getNftSource(){if(!nftSourcePromise)nftSourcePromise=fetch(NFT_SOURCE,{cache:"force-cache"}).then(r=>{if(!r.ok)throw new Error("NFT source unavailable");return r.json()});return nftSourcePromise}
async function getNftAttributes(shortName,gift){if(nftAttrCache.has(shortName))return nftAttrCache.get(shortName);const path=gift&&gift.models?String(gift.models).replace(/^\//,""):"models/"+shortName+"/prices.json";const p=fetch(NFT_BASE+path+"?v=20261004",{cache:"no-store"}).then(r=>{if(!r.ok)throw new Error("Gift attributes unavailable");return r.json()});nftAttrCache.set(shortName,p);return p}
function nftGiftCatalog(data){return (data.upgraded||[]).filter(x=>x&&x.full_name&&x.models).map(x=>({...x,type:"collectible"})).sort((a,b)=>a.full_name.localeCompare(b.full_name))}
function nftSellUsd(n){return Number(n||0)*TON_TO_USD*(1+NFT_COST_BUFFER)*(1+NFT_PROFIT)}
function tonUsd(n){return nftSellUsd(n).toLocaleString("en-US",{style:"currency",currency:"USD",minimumFractionDigits:2,maximumFractionDigits:2})}
function tonMoney(n){return Number(n||0).toLocaleString("en-US",{maximumFractionDigits:4})+" TON · "+tonUsd(n)}
function money(n){return Number(n||0).toLocaleString("en-US")+" USD"}
function numericPrice(text){const n=Number(String(text||"").replace(/[^0-9.]/g,""));return Number.isFinite(n)?n:0}
function starsPrice(n){n=Number(n||0);if(n<=0)return 0;if(n<=50)return n*225/50;if(n<=100)return 225+(n-50)*(445-225)/50;if(n<=150)return 445+(n-100)*(655-445)/50;if(n<=200)return 655+(n-150)*(865-655)/50;return 865+(n-200)*(1080-865)/50}
function cartItemTotalUsd(x){if(Number.isFinite(Number(x.totalUsd)))return Number(x.totalUsd);if(Number.isFinite(Number(x.totalToman)))return Number(x.totalToman)/USD_TO_TOMAN;if(x.currency==="TON"&&Number.isFinite(Number(x.total)))return nftSellUsd(Number(x.total));if(Number.isFinite(Number(x.total)))return Number(x.total);return numericPrice(x.price)*Number(x.quantity||1)}
function nftImageUrl(shortName){return NFT_BASE+"webp/by_name/"+encodeURIComponent(shortName)+".webp"}
function modelFileName(modelName){return String(modelName||"").trim().toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_+|_+$/g,"")}
function modelImageUrl(shortName,modelName){return MODEL_ASSET_BASE+encodeURIComponent(shortName)+"/"+encodeURIComponent(modelFileName(modelName))+".webp"}
function modelTgsUrl(shortName,modelName){return MODEL_ASSET_BASE+encodeURIComponent(shortName)+"/"+encodeURIComponent(modelFileName(modelName))+".tgs"}
async function animateTgs(container,url){if(!container||!window.lottie||!window.pako)return false;try{const r=await fetch(url,{cache:"force-cache"});if(!r.ok)throw new Error("TGS unavailable");const raw=new Uint8Array(await r.arrayBuffer());const json=JSON.parse(window.pako.ungzip(raw,{to:"string"}));container.innerHTML="";window.lottie.loadAnimation({container,renderer:"svg",loop:true,autoplay:true,animationData:json});return true}catch(e){console.warn("TGS animation unavailable",e);return false}}
let cart=JSON.parse(localStorage.getItem("pikoya-cart")||"[]");
let orders=JSON.parse(localStorage.getItem("pikoya-orders")||"[]");
let favorites=JSON.parse(localStorage.getItem("pikoya-favorites")||"[]");
const app=document.getElementById("app");
const C=id=>document.getElementById(id);
function save(){localStorage.setItem("pikoya-cart",JSON.stringify(cart));localStorage.setItem("pikoya-orders",JSON.stringify(orders));localStorage.setItem("pikoya-favorites",JSON.stringify(favorites));updateCount()}
function updateCount(){document.getElementById("cart-count").textContent=cart.length}
function shell(title,body){return '<section class="page"><div class="wrap"><div class="eyebrow">Pikoya</div><h1>'+title+'</h1>'+body+'</div></section>'}
function home(){return '<div class="wrap"><section class="hero"><div class="hero-card"></div></section><h2 class="section-title">The collection</h2><div class="services">'+Object.entries(services).map(([k,s])=>card(k,s)).join("")+'</div></div>'}
function card(k,s){return '<article class="service"><a class="service-link" href="#service/'+k+'"><img class="service-banner" loading="lazy" decoding="async" src="'+(k==="nft"?"file_000000008618821089451802e626503f.png":k==="stars"?"stars-banner.png":k+".png")+'" alt="'+s.name+' service"></a><div class="service-info"><div><h3>'+s.name+'</h3></div><a class="btn alt" href="#service/'+k+'">View service</a></div></article>'}
function nftPage(){return shell("NFT",'<div class="nft-market"><div class="nft-market-head"><div><div class="eyebrow">Pikoya NFT</div><h2>Collections</h2><p>Choose a collection to view all of its models and Backdrops.</p></div><div class="nft-market-count" id="nftMarketCount">Loading…</div></div><div class="nft-toolbar product-box"><div class="nft-search-wide"><label for="nftSearch">Search collections</label><input id="nftSearch" placeholder="e.g. Jingle Bells"></div><div class="nft-filter-grid nft-filter-main"><div><label for="nftSort">Sort</label><select id="nftSort"><option value="featured">Featured</option><option value="priceAsc">Price: low to high</option><option value="priceDesc">Price: high to low</option><option value="name">Name</option></select></div></div></div><div id="nftSourceStatus" class="field-hint nft-status">Loading collections…</div><details class="nft-collection-dropdown" open><summary><strong>NFT Collections</strong><span>Browse all collections</span></summary><div class="nft-collection-shell"><div id="nftResults" class="nft-market-grid"></div></div></details></div>')}

function nftGiftPage(shortName){return shell("NFT",'<div class="nft-detail-page" data-nft-gift="'+encodeURIComponent(shortName||"")+'"><div class="nft-detail-top"><a class="btn alt" href="#service/nft">← All collections</a><div><div class="eyebrow">NFT Collection</div><h2 id="nftDetailTitle">Loading…</h2><p id="nftDetailIntro">Choose a model and Backdrop from this collection.</p></div></div><div id="nftSourceStatus" class="field-hint nft-status">Loading models…</div><div id="nftResults" style="display:none"></div><div id="nftModels" class="nft-models-panel"></div><div id="nftCalculator" class="product-box nft-buy-panel" style="display:none"><div class="nft-buy-head"><div><div class="eyebrow">Selected Model</div><h2 id="nftSelectedName">—</h2></div><button class="btn alt" id="nftCloseSelection" type="button">Clear</button></div><div class="nft-buy-layout"><div class="nft-buy-preview"><div id="nftSelectedArt" class="nft-selected-art"></div><div id="nftSelectedDetails">—</div></div><div class="nft-buy-form"><label for="nftQty">Quantity</label><input id="nftQty" type="number" min="1" value="1"><div class="nft-total"><span>Total</span><strong id="nftTotal">—</strong></div><label for="nftUsername">Username / ID</label><input id="nftUsername" placeholder="@username"><label for="nftNote">Order note (optional)</label><textarea id="nftNote" rows="3" placeholder="Anything we should know?"></textarea><button class="btn gold" id="nftAddCart">Add to cart</button></div></div></div></div>')}
function servicePage(key){if(key==="nft")return nftPage();let s=services[key];if(!s)return home();let custom=key==="stars"?'<div class="custom-stars"><label for="customStars">Custom Stars amount</label><input id="customStars" type="number" min="1" step="1" placeholder="e.g. 170"><div id="customStarsPrice" class="custom-stars-price">Enter an amount</div><small class="field-hint">Use this instead of selecting a preset plan.</small></div>':'';let boostHint=key==="boost"?'<small class="field-hint">Minimum: 15 for 1 Day, 5 for 1 Month. Other plans: any amount.</small>':'';return shell(s.name,'<div class="product-box purchase-box"><h2 class="purchase-title">'+s.name+'</h2><p class="sub"'+(s.desc?'':' style="display:none"')+'>'+s.desc+'</p><label>Choose a plan / amount</label><div class="plans">'+s.plans.map((p,i)=>'<button class="plan'+((key==="premium"&&i===0)?' disabled':'')+'" data-plan="'+i+'"'+((key==="premium"&&i===0)?' disabled aria-disabled="true"':'')+'><strong>'+p[0]+'</strong><br><span class="price">'+p[1]+'</span></button>').join("")+'</div>'+custom+'<label for="username">Username / ID</label><input id="username" placeholder="@username"><label for="quantity">Quantity</label><input id="quantity" type="number" min="1" value="1">'+boostHint+'<label for="note">Order note (optional)</label><textarea id="note" rows="3" placeholder="Anything we should know?"></textarea><br><br><button class="btn gold" id="addCart">Add to cart</button></div>')}
function search(){return shell("Search",'<div class="product-box"><input id="searchInput" placeholder="Search Premium, Stars, Boost, NFT..."></div><div class="services" id="searchResults" style="margin-top:20px">'+Object.entries(services).map(([k,s])=>card(k,s)).join("")+'</div>')}
function cartPage(){if(!cart.length)return shell("Cart",'<div class="empty">Your basket is quiet for now.<br><br><a class="btn gold" href="#home">Shop services</a></div>');let total=cart.reduce((sum,x)=>sum+cartItemTotalUsd(x),0);return shell("Cart",'<div class="product-box">'+cart.map((x,i)=>'<div style="display:flex;justify-content:space-between;gap:15px;padding:15px 0;border-bottom:1px solid var(--line)"><div><strong>'+x.name+'</strong><br><small>'+x.plan+' × '+(x.quantity||1)+' • '+(x.username||"No username")+'</small>'+(x.backdrop?'<br><small>Backdrop: '+x.backdrop+'</small>':'')+'<br><b>'+Number(cartItemTotalUsd(x)).toLocaleString("en-US")+' USD</b></div><button class="btn alt" data-remove="'+i+'">Remove</button></div>').join("")+'<div style="display:flex;justify-content:space-between;padding:18px 0"><strong>Total</strong><strong>'+total.toLocaleString("en-US")+' USD</strong></div><button class="btn gold" id="checkout">Continue to checkout</button></div>')}
function account(){return shell("My Account",'<div class="product-box"><div class="notice">Account UI is ready. Secure SMS authentication needs a server-side provider before launch; GitHub Pages cannot safely send or verify private SMS codes by itself.</div><label>Phone number</label><input placeholder="+..."><label>Password</label><input type="password" placeholder="••••••••"><br><br><button class="btn gold">Sign in</button> <button class="btn alt">Create account</button></div>')}
function ordersPage(){if(!orders.length)return shell("My Orders",'<div class="empty">No orders yet.</div>');return shell("My Orders",'<table class="table"><thead><tr><th>Order</th><th>Details</th><th>Amount</th><th>Status</th></tr></thead><tbody>'+orders.map(o=>'<tr><td>'+o.id+'</td><td>'+o.details+'</td><td>'+o.amount+'</td><td class="status">'+o.status+'</td></tr>').join("")+'</tbody></table>')}
function guide(){return shell("Help / Guide",'<div class="faq"><details open><summary>How do I order?</summary><p>Select a service, choose a plan, enter your @username and add it to your cart. Then continue to checkout.</p></details><details><summary>What happens after checkout?</summary><p>Your order receives a number and status. The final supplier/payment connection will be added before production launch.</p></details><details><summary>Can I see my order later?</summary><p>Yes. My Orders is prepared to show order number, details, amount and status.</p></details></div>')}
function simple(title,text){return shell(title,'<div class="product-box"><p class="sub">'+text+'</p></div>')}
function render(){let hash=location.hash.slice(1)||"home";let [route,arg,subarg]=hash.split("/");let html=route==="home"?home():route==="search"?search():route==="service"?(arg==="nftgift"?nftGiftPage(decodeURIComponent(subarg||"")):servicePage(arg)):route==="cart"?cartPage():route==="account"?account():route==="orders"?ordersPage():route==="guide"?guide():route==="settings"?simple("Settings","Site settings will live here."):route==="favorites"?simple("Favorites",favorites.length?favorites.join(", "):"No favorites yet."):route==="support"?simple("Support","For launch, add the official Pikoya support contact here."):home();app.innerHTML=html;bind();updateCount()}
function bind(){document.querySelectorAll(".plan").forEach((b,i)=>b.onclick=()=>{document.querySelectorAll(".plan").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");b.dataset.selected="true"});let cs=document.getElementById("customStars"),cp=document.getElementById("customStarsPrice");if(cs&&cp)cs.oninput=()=>{let n=Number(cs.value);if(!n||n<1){cp.textContent="Enter an amount";return}let price;if(n<=50){price=n*225/50}else if(n<=100){price=225+(n-50)*(445-225)/50}else if(n<=150){price=445+(n-100)*(655-445)/50}else if(n<=200){price=655+(n-150)*(865-655)/50}else{price=865+(n-200)*(1080-865)/50}cp.textContent=Math.round(price).toLocaleString("en-US")+" USD"};let add=document.getElementById("addCart");if(add)add.onclick=()=>{let key=location.hash.split("/")[1],qty=Math.max(1,Number(document.getElementById("quantity").value||1)),custom=document.getElementById("customStars"),customAmount=custom?Number(custom.value||0):0,selected=document.querySelector(".plan.selected");if(key==="stars"&&customAmount>0){let unit=Math.round(starsPrice(customAmount));cart.push({name:"Stars",plan:customAmount+" Stars",quantity:1,unitPrice:unit,total:unit,price:unit,username:document.getElementById("username").value,note:document.getElementById("note").value});save();alert("Added to cart.");location.hash="#cart";return}if(!selected)return alert("Choose a plan or enter a custom Stars amount.");if(key==="boost"){let pi=Number(selected.dataset.plan||0),min=pi===0?15:pi===1?5:1;if(qty<min)return alert("Minimum quantity for this Boost plan is "+min+".")}let s=services[key],unit=numericPrice(s.plans[Number(selected.dataset.plan||0)][1]);cart.push({name:s.name,plan:s.plans[Number(selected.dataset.plan||0)][0],quantity:qty,unitPrice:unit,total:unit*qty,price:unit,username:document.getElementById("username").value,note:document.getElementById("note").value});save();alert("Added to cart.");location.hash="#cart"};document.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{cart.splice(Number(b.dataset.remove),1);save();render()});let checkout=document.getElementById("checkout");if(checkout)checkout.onclick=()=>{let id="PKY-"+Date.now().toString().slice(-7),total=cart.reduce((sum,x)=>sum+cartItemTotalUsd(x),0);orders.unshift({id,details:cart.map(x=>x.name+" / "+x.plan+(x.backdrop?" / Backdrop: "+x.backdrop:"")).join(", "),amount:total.toLocaleString("en-US")+" USD",status:"pending"});cart=[];save();alert("Order created: "+id);location.hash="#orders"};let si=document.getElementById("searchInput");if(si)si.oninput=()=>{let q=si.value.toLowerCase();document.getElementById("searchResults").innerHTML=Object.entries(services).filter(([k,s])=>(k+" "+s.desc).toLowerCase().includes(q)).map(([k,s])=>card(k,s)).join("")};
let nr=document.getElementById("nftResults");
if(nr){
 const C=id=>document.getElementById(id);
 const search=C("nftSearch"),sort=C("nftSort"),models=C("nftModels"),status=C("nftSourceStatus"),calc=C("nftCalculator"),selectedName=C("nftSelectedName"),selectedArt=C("nftSelectedArt"),selectedDetails=C("nftSelectedDetails"),qty=C("nftQty");
 let allGifts=[],selectedGift=null,attrs=null,selectedModel="",selectedBackdrop="";
 function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
 function giftFloor(g){return Number(g.floor_price_ton??g.portal_price_ton??g.getgems_price_ton??g.tgmrkt_price_ton??0)} function normalizeAttrs(raw){if(!raw)return {models:{},backdrops:{},symbols:{}};const prices=v=>Array.isArray(v)?Object.fromEntries(v.filter(x=>x&&x.name).map(x=>[x.name,Number(x.price??x.price_ton??0)])):v||{};const bds=Array.isArray(raw.backdrops)?Object.fromEntries(raw.backdrops.filter(x=>x&&x.name).map(x=>[x.name,x])):Object.fromEntries(Object.entries(raw.backdrops||{}).map(([k,v])=>[k,typeof v==="object"?v:{price:Number(v||0)}]));return {models:prices(raw.models),backdrops:bds,symbols:prices(raw.symbols||raw.patterns)} }
 function backdropFor(name){return attrs&&attrs.backdrops?attrs.backdrops[name]||null:null}
 function rgbHex(v){if(typeof v==="string"){if(v.startsWith("#"))return v;return v}if(typeof v==="number")return "#"+v.toString(16).padStart(6,"0");return "#d8b477"}
 function backdropColor(name){const b=backdropFor(name)||{};const h=b.colors||b.hex||b;return rgbHex(h.centerColor??h.center_color??h.center??h.color)}
 function backdropStyle(name){return "background:"+backdropColor(name)}
 function modelPrice(name){return attrs&&attrs.models?Number(attrs.models[name]||0):0}
 function renderGifts(){
   const q=(search.value||"").trim().toLowerCase();
   let list=allGifts.filter(g=>!q||(g.full_name+" "+g.short_name).toLowerCase().includes(q));
   if(sort.value==="priceAsc")list.sort((a,b)=>giftFloor(a)-giftFloor(b));
   else if(sort.value==="priceDesc")list.sort((a,b)=>giftFloor(b)-giftFloor(a));
   else if(sort.value==="name")list.sort((a,b)=>a.full_name.localeCompare(b.full_name));
   nr.innerHTML=list.map(g=>'<button class="nft-market-card" data-gift-short="'+esc(g.short_name)+'"><div class="nft-gift-thumb"><img loading="lazy" decoding="async" src="'+esc(nftImageUrl(g.short_name))+'" alt="'+esc(g.full_name)+'"></div><div class="nft-gift-main"><strong>'+esc(g.full_name)+'</strong><small>'+esc(g.type==="collectible"?"Collection":g.type||"Collection")+'</small></div><div class="nft-gift-action"><span>›</span></div></button>').join("")||'<div class="empty">No collections found.</div>';
   document.querySelectorAll("[data-gift-short]").forEach(b=>b.onclick=()=>openGift(b.dataset.giftShort));
   status.textContent=list.length+" Collection ready to browse.";
 }
async function openGift(shortName){
   selectedGift=allGifts.find(g=>g.short_name===shortName)||null;selectedModel="";selectedBackdrop="";attrs=null;
   if(!selectedGift)return;
   if(!document.querySelector(".nft-detail-page")){location.hash="#service/nftgift/"+encodeURIComponent(shortName);return}
   const detailTitle=document.getElementById("nftDetailTitle");if(detailTitle)detailTitle.textContent=selectedGift.full_name;
   models.innerHTML='<div class="empty">Loading all models for '+esc(selectedGift.full_name)+'…</div>';
   models.scrollIntoView({behavior:"smooth",block:"start"});
   try{
     attrs=await getNftAttributes(selectedGift.short_name,selectedGift);
     const names=Object.keys(attrs.models||{}).sort((a,b)=>Number(attrs.models[a])-Number(attrs.models[b]));
     const defaultBackdrop=(Object.keys(attrs.backdrops||{})[0]||"");
     models.innerHTML='<div class="nft-models-head"><div><div class="eyebrow">Models</div><h3>'+esc(selectedGift.full_name)+'</h3><p>'+names.length+' models available · click a model for details.</p></div><div class="nft-rate">Base rate: 1 TON = $1.54 · +3% costs · +10% profit</div></div><div class="nft-model-grid">'+names.map((name,i)=>'<button class="nft-model-card" data-model-name="'+esc(name)+'"><div class="nft-model-art" style="'+backdropStyle(defaultBackdrop)+'"><div class="nft-animated-art" data-tgs="'+esc(modelTgsUrl(selectedGift.short_name,name))+'"><img loading="lazy" decoding="async" src="'+esc(modelImageUrl(selectedGift.short_name,name))+'" alt="'+esc(name)+'"></div><span>'+esc(defaultBackdrop)+'</span></div><div class="nft-model-copy"><strong>'+esc(name)+'</strong><b>'+tonUsd(modelPrice(name))+'</b><small>'+modelPrice(name).toLocaleString("en-US")+' TON</small></div></button>').join("")+'</div>';
     document.querySelectorAll("[data-model-name]").forEach(b=>b.onclick=()=>selectModel(b.dataset.modelName));
     document.querySelectorAll(".nft-animated-art[data-tgs]").forEach(el=>animateTgs(el,el.dataset.tgs));
     status.textContent=allGifts.length+" gift in the catalog · "+names.length+" models for this gift.";
   }catch(e){
     console.error("NFT attributes error",e);
     const fallbackNames=Object.keys((selectedGift&&selectedGift.models_data)||{});
     models.innerHTML='<div class="empty">Models for this collection are currently unavailable.<br><small>'+esc(e.message||"Unknown error")+'</small></div>'
   }
 }
 function selectModel(name){
   selectedModel=name;calc.style.display="block";selectedName.textContent=selectedGift.full_name+" · "+name;
   const backdropNames=Object.keys(attrs.backdrops||{});
   selectedBackdrop=selectedBackdrop&&attrs.backdrops[selectedBackdrop]?selectedBackdrop:(backdropNames[0]||"");
   const options=backdropNames.map(b=>'<button type="button" class="nft-backdrop-choice'+(b===selectedBackdrop?" selected":"")+'" data-backdrop-name="'+esc(b)+'"><i style="'+backdropStyle(b)+'"></i><span>'+esc(b)+'</span><small>'+Number(attrs.backdrops[b]?.price||attrs.backdrops[b]||0).toLocaleString("en-US")+' TON</small></button>').join("");
   selectedArt.innerHTML='<div class="nft-selected-stage" style="'+backdropStyle(selectedBackdrop)+'"><div class="nft-animated-art" id="nftSelectedAnimation" data-tgs="'+esc(modelTgsUrl(selectedGift.short_name,name))+'"><img src="'+esc(modelImageUrl(selectedGift.short_name,name))+'" alt="'+esc(name)+'"></div></div><div class="nft-backdrop-label">Backdrop / Backdrop color</div><div class="nft-backdrop-grid">'+(options||'<span class="nft-backdrop-empty">No Backdrop available</span>')+'</div>';
   document.querySelectorAll("[data-backdrop-name]").forEach(b=>b.onclick=()=>{selectedBackdrop=b.dataset.backdropName;document.querySelectorAll(".nft-backdrop-choice").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");selectedArt.querySelector(".nft-selected-stage").setAttribute("style",backdropStyle(selectedBackdrop));updateTotal()});
   animateTgs(document.getElementById("nftSelectedAnimation"),modelTgsUrl(selectedGift.short_name,name));
   updateTotal();
   calc.scrollIntoView({behavior:"smooth",block:"center"});
 }
 function updateTotal(){if(!selectedGift||!selectedModel)return;const unit=modelPrice(selectedModel)||giftFloor(selectedGift),q=Math.max(1,Number(qty.value)||1);document.getElementById("nftTotal").textContent=tonUsd(unit*q);selectedDetails.innerHTML='<strong>'+esc(selectedGift.full_name)+'</strong><br>Model: '+esc(selectedModel)+'<br>Backdrop: '+esc(selectedBackdrop||"Default")+'<br><b>'+unit.toLocaleString("en-US")+' TON · '+tonUsd(unit)+' each</b>'}
 qty&&qty.addEventListener("input",updateTotal);
 const clear=C("nftCloseSelection");if(clear)clear.onclick=()=>{selectedGift=null;selectedModel="";selectedBackdrop="";attrs=null;calc.style.display="none";models.innerHTML="";window.scrollTo({top:0,behavior:"smooth"})};
 const na=C("nftAddCart");if(na)na.onclick=()=>{if(!selectedGift||!selectedModel)return alert("Choose a model first.");const q=Math.max(1,Number(qty.value)||1),unit=modelPrice(selectedModel)||giftFloor(selectedGift);cart.push({name:"NFT · "+selectedGift.full_name,plan:"Model: "+selectedModel,backdrop:selectedBackdrop||"Default",quantity:q,unitPrice:unit,total:unit*q,currency:"TON",totalUsd:nftSellUsd(unit*q),username:C("nftUsername").value,note:C("nftNote").value});save();alert("Added to cart.");location.hash="#cart"};
 if(search&&sort){search.addEventListener("input",renderGifts);sort.addEventListener("change",renderGifts)}
 async function init(){try{const source=await getNftSource();allGifts=nftGiftCatalog(source);status.textContent=allGifts.length+" Collection loaded from the latest source.";const detail=document.querySelector(".nft-detail-page");if(detail){const initial=decodeURIComponent(detail.dataset.nftGift||"");if(initial)await openGift(initial)}else{renderGifts()}}catch(e){status.textContent="Catalog connection is currently unavailable.";nr.innerHTML='<div class="empty">Gift catalog is currently unavailable.</div>'}}
 init();
}
}
window.addEventListener("hashchange",render);render();

const drawer=document.getElementById("drawer"),backdrop=document.getElementById("backdrop");
document.getElementById("menuBtn").onclick=()=>{drawer.classList.add("open");backdrop.classList.add("open")};
document.getElementById("drawerClose").onclick=()=>{drawer.classList.remove("open");backdrop.classList.remove("open")};
backdrop.onclick=()=>{drawer.classList.remove("open");backdrop.classList.remove("open")};
document.querySelectorAll(".drawer a").forEach(a=>a.onclick=()=>{drawer.classList.remove("open");backdrop.classList.remove("open")});
