const services={
 premium:{name:"Premium",mark:"P",desc:"",plans:[["1 Month",""],["3 Months","3,300 / 3,600 تومان"],["6 Months","4,300 / 4,600 تومان"],["12 Months","7,800 / 8,150 تومان"]]},
 stars:{name:"Stars",mark:"S",desc:"",plans:[["50 Stars","— تومان"],["100 Stars","— تومان"],["250 Stars","— تومان"],["500 Stars","— تومان"]]},
 boost:{name:"Boost",mark:"B",desc:"",plans:[["1 Boost","— تومان"],["4 Boosts","— تومان"],["7 Boosts","— تومان"],["14 Boosts","— تومان"]]},
 nft:{name:"NFT",mark:"N",desc:"",plans:[["Basic","— تومان"],["Classic","— تومان"],["Premium","— تومان"],["Custom","— تومان"]]}
};
let cart=JSON.parse(localStorage.getItem("pikoya-cart")||"[]");
let orders=JSON.parse(localStorage.getItem("pikoya-orders")||"[]");
let favorites=JSON.parse(localStorage.getItem("pikoya-favorites")||"[]");
const app=document.getElementById("app");
function save(){localStorage.setItem("pikoya-cart",JSON.stringify(cart));localStorage.setItem("pikoya-orders",JSON.stringify(orders));localStorage.setItem("pikoya-favorites",JSON.stringify(favorites));updateCount()}
function updateCount(){document.getElementById("cart-count").textContent=cart.length}
function shell(title,body){return '<section class="page"><div class="wrap"><div class="eyebrow">Pikoya</div><h1>'+title+'</h1>'+body+'</div></section>'}
function home(){return '<div class="wrap"><section class="hero"><div class="hero-card"></div></section><h2 class="section-title">The collection</h2><div class="services">'+Object.entries(services).map(([k,s])=>card(k,s)).join("")+'</div></div>'}function card(k,s){return '<article class="service"><a class="service-link" href="#service/'+k+'"><img class="service-banner" loading="lazy" decoding="async" src="'+(k==="nft"?"file_000000008618821089451802e626503f.png":k==="stars"?"stars-banner.png":k+".png")+'" alt="'+s.name+' service"></a><div class="service-info"><div><h3>'+s.name+'</h3></div><a class="btn alt" href="#service/'+k+'">View service</a></div></article>'}
function servicePage(key){let s=services[key];if(!s)return home();return shell(s.name,'<div class="product-box purchase-box"><h2 class="purchase-title">'+s.name+'</h2><p class="sub"'+(s.desc?'':' style="display:none"')+'>'+s.desc+'</p><label>Choose a plan / amount</label><div class="plans">'+s.plans.map((p,i)=>'<button class="plan'+((key==="premium"&&i===0)?' disabled':'')+'" data-plan="'+i+'"'+((key==="premium"&&i===0)?' disabled aria-disabled="true"':'')+'><strong>'+p[0]+'</strong><br><span class="price">'+p[1]+'</span></button>').join("")+'</div><label for="username">Username / ID</label><input id="username" placeholder="@username"><label for="quantity">Quantity</label><input id="quantity" type="number" min="1" value="1"><label for="note">Order note (optional)</label><textarea id="note" rows="3" placeholder="Anything we should know?"></textarea><br><br><button class="btn gold" id="addCart">Add to cart</button></div>')}
function search(){return shell("Search",'<div class="product-box"><input id="searchInput" placeholder="Search Premium, Stars, Boost, NFT..."></div><div class="services" id="searchResults" style="margin-top:20px">'+Object.entries(services).map(([k,s])=>card(k,s)).join("")+'</div>')}
function cartPage(){if(!cart.length)return shell("Cart",'<div class="empty">Your basket is quiet for now.<br><br><a class="btn gold" href="#home">Shop services</a></div>');let total=cart.length;return shell("Cart",'<div class="product-box">'+cart.map((x,i)=>'<div style="display:flex;justify-content:space-between;gap:15px;padding:15px 0;border-bottom:1px solid var(--line)"><div><strong>'+x.name+'</strong><br><small>'+x.plan+' • '+(x.username||"No username")+'</small></div><button class="btn alt" data-remove="'+i+'">Remove</button></div>').join("")+'<p><strong>'+total+' item(s)</strong></p><button class="btn gold" id="checkout">Continue to checkout</button></div>')}
function account(){return shell("My Account",'<div class="product-box"><div class="notice">Account UI is ready. Secure SMS authentication needs a server-side provider before launch; GitHub Pages cannot safely send or verify private SMS codes by itself.</div><label>Phone number</label><input placeholder="+..."><label>Password</label><input type="password" placeholder="••••••••"><br><br><button class="btn gold">Sign in</button> <button class="btn alt">Create account</button></div>')}
function ordersPage(){if(!orders.length)return shell("My Orders",'<div class="empty">No orders yet.</div>');return shell("My Orders",'<table class="table"><thead><tr><th>Order</th><th>Details</th><th>Amount</th><th>Status</th></tr></thead><tbody>'+orders.map(o=>'<tr><td>'+o.id+'</td><td>'+o.details+'</td><td>'+o.amount+'</td><td class="status">'+o.status+'</td></tr>').join("")+'</tbody></table>')}
function guide(){return shell("Help / Guide",'<div class="faq"><details open><summary>How do I order?</summary><p>Select a service, choose a plan, enter your @username and add it to your cart. Then continue to checkout.</p></details><details><summary>What happens after checkout?</summary><p>Your order receives a number and status. The final supplier/payment connection will be added before production launch.</p></details><details><summary>Can I see my order later?</summary><p>Yes. My Orders is prepared to show order number, details, amount and status.</p></details></div>')}
function simple(title,text){return shell(title,'<div class="product-box"><p class="sub">'+text+'</p></div>')}
function render(){let hash=location.hash.slice(1)||"home";let [route,arg]=hash.split("/");let html=route==="home"?home():route==="search"?search():route==="service"?servicePage(arg):route==="cart"?cartPage():route==="account"?account():route==="orders"?ordersPage():route==="guide"?guide():route==="settings"?simple("Settings","Site settings will live here."):route==="favorites"?simple("Favorites",favorites.length?favorites.join(", "):"No favorites yet."):route==="support"?simple("Support","For launch, add the official Pikoya support contact here."):home();app.innerHTML=html;bind();updateCount()}
function bind(){document.querySelectorAll(".plan").forEach((b,i)=>b.onclick=()=>{document.querySelectorAll(".plan").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");b.dataset.selected="true"});let add=document.getElementById("addCart");if(add)add.onclick=()=>{let selected=document.querySelector(".plan.selected");if(!selected)return alert("Choose a plan first.");let key=location.hash.split("/")[1];let s=services[key];cart.push({name:s.name,plan:s.plans[Number(selected.dataset.plan||0)][0],username:document.getElementById("username").value,note:document.getElementById("note").value});save();alert("Added to cart.");location.hash="#cart"};document.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{cart.splice(Number(b.dataset.remove),1);save();render()});let checkout=document.getElementById("checkout");if(checkout)checkout.onclick=()=>{let id="PKY-"+Date.now().toString().slice(-7);orders.unshift({id,details:cart.map(x=>x.name+" / "+x.plan).join(", "),amount:"—",status:"pending"});cart=[];save();alert("Order created: "+id);location.hash="#orders"};let si=document.getElementById("searchInput");if(si)si.oninput=()=>{let q=si.value.toLowerCase();document.getElementById("searchResults").innerHTML=Object.entries(services).filter(([k,s])=>(k+" "+s.desc).toLowerCase().includes(q)).map(([k,s])=>card(k,s)).join("")}}
window.addEventListener("hashchange",render);render();

const drawer=document.getElementById("drawer"),backdrop=document.getElementById("backdrop");
document.getElementById("menuBtn").onclick=()=>{drawer.classList.add("open");backdrop.classList.add("open")};
document.getElementById("drawerClose").onclick=()=>{drawer.classList.remove("open");backdrop.classList.remove("open")};
backdrop.onclick=()=>{drawer.classList.remove("open");backdrop.classList.remove("open")};
document.querySelectorAll(".drawer a").forEach(a=>a.onclick=()=>{drawer.classList.remove("open");backdrop.classList.remove("open")});
